{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ template "releaseName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "releaseName" . }}
{{- end }}
