{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ template "releaseName" . }}
  {{- with .Values.rbac.rules }}
rules:
{{ toYaml . | trim | indent 2 }}
  {{- end }}
{{- end }}
